import Link from "next/link";
import { ArrowLeft, BookOpen, ChevronRight, ExternalLink, Layers3 } from "lucide-react";
import type { BookResource, Locale } from "@/types";
export function BookDetail({locale,book}:{locale:Locale;book:BookResource}){
 const id=locale==="id";
 return <div className="space-y-5"><Link href={`/${locale}/library`} className="btn-ghost"><ArrowLeft size={17}/>{id?"Kembali ke Library":"ライブラリーへ"}</Link><section className="card p-6 md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className="badge border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{book.series}</span><span className="badge border-slate-200 dark:border-slate-700">{book.level}</span><span className="badge border-slate-200 dark:border-slate-700">{book.chapterMapping}</span></div><h1 className="mt-4 text-3xl font-black md:text-4xl">{book.title}</h1><p className="mt-3 max-w-3xl text-slate-600 dark:text-slate-300">{book.description}</p><p className="mt-3 text-xs text-slate-400">{id?"Catatan: Kezett tidak menyalin isi buku lengkap. Materi di bawah berupa peta bab, poin belajar, contoh baru, dan tes original yang disesuaikan dengan level sumber.":"Kezettは書籍本文を複製せず、章マップ・学習ポイント・新規例文・オリジナル章テストを提供します。"}</p></div><a target="_blank" rel="noreferrer" href={book.sourceUrl} className="btn-primary"><ExternalLink size={17}/>{id?"Buka sumber asli":"原典を開く"}</a></div></section>
 <section className="soft-card p-4"><div className="text-xs font-black uppercase tracking-wider text-slate-400">{id?"Sumber yang terdeteksi di Drive":"Driveで確認した資料"}</div><div className="mt-3 flex flex-wrap gap-2">{book.sourceFiles.map(f=><span key={f} className="badge border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900">{f}</span>)}</div></section>
 {book.chapters.length===0?<section className="card p-6"><Layers3 className="text-emerald-600"/><h2 className="mt-3 text-xl font-black">{id?"Koleksi referensi":"参考資料コレクション"}</h2><p className="mt-2 text-slate-500">{id?"Koleksi ini disimpan sebagai referensi lanjutan dan tidak dipaksakan menjadi bab JFT.":"この資料は上級参考用で、JFT章としては扱いません。"}</p><div className="mt-4 flex flex-wrap gap-2">{book.sourceFiles.map(f=><span key={f} className="badge border-slate-200 dark:border-slate-700">{f}</span>)}</div></section>:<section><div className="mb-4 flex items-center gap-2"><BookOpen className="text-emerald-600"/><h2 className="text-xl font-black">{id?"Bab / Unit":"章 / ユニット"}</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{book.chapters.map(ch=><Link key={ch.id} href={`/${locale}/library/${book.id}/${ch.id}`} className="soft-card group p-5 transition hover:border-emerald-300 hover:bg-white dark:hover:bg-slate-900"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-wider text-emerald-600">{id?"Bab":"Lesson"} {ch.number}</span><span className="badge border-slate-200 dark:border-slate-700">{ch.level}</span></div><h3 className="mt-3 font-black leading-snug">{ch.title}</h3><p className="mt-2 text-sm text-slate-500">{ch.topic}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-400"><span>{ch.vocabulary.length} vocab · {ch.grammar.length} pola</span><ChevronRight size={17} className="transition group-hover:translate-x-1"/></div></Link>)}</div></section>}</div>
}
