"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { BookMarked, ChevronRight, ExternalLink, LibraryBig, Search } from "lucide-react";
import type { Locale } from "@/types";
import { bookLibrary, chapterCount, librarySourceRoot } from "@/data/bookLibrary";

const priorityStyle={core:"border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300",support:"border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-300",outside:"border-slate-200 bg-slate-50 text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300"};
export function BookLibrary({locale}:{locale:Locale}){
 const id=locale==="id"; const [query,setQuery]=useState(""); const [filter,setFilter]=useState<"all"|"core"|"support"|"outside">("all");
 const items=useMemo(()=>bookLibrary.filter(b=>(filter==="all"||b.jftPriority===filter)&&(`${b.title} ${b.series} ${b.description}`.toLowerCase().includes(query.toLowerCase()))),[query,filter]);
 return <div className="space-y-6"><section className="card p-6 md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-emerald-600"><LibraryBig/><span className="text-xs font-black uppercase tracking-[.16em]">Kezett Library</span></div><h1 className="mt-3 text-3xl font-black md:text-4xl">{id?"Belajar dari Buku":"教材ライブラリー"}</h1><p className="mt-3 max-w-3xl text-slate-600 dark:text-slate-300">{id?`Semua sumber buku dari Drive dipetakan menjadi jalur belajar per bab. Kezett menyimpan ${chapterCount} unit/bab untuk belajar, review, dan tes bab original sesuai tingkat materi.`:`Driveの教材を章ごとの学習ルートに整理。${chapterCount}ユニットで学習・復習・章テストができます。`}</p></div><a className="btn-ghost border border-slate-200 dark:border-slate-700" target="_blank" rel="noreferrer" href={librarySourceRoot}><ExternalLink size={17}/>{id?"Buka folder sumber":"Driveを開く"}</a></div></section>
 <section className="flex flex-col gap-3 md:flex-row"><label className="soft-card flex flex-1 items-center gap-3 px-4 py-3"><Search size={18} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent outline-none" placeholder={id?"Cari Irodori, Minna, kanji, bunpou...":"教材を検索..."}/></label><div className="flex flex-wrap gap-2">{(["all","core","support","outside"] as const).map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-xl px-4 py-2 text-sm font-black ${filter===x?"bg-slate-900 text-white dark:bg-white dark:text-slate-900":"soft-card"}`}>{x==="all"?(id?"Semua":"すべて"):x==="core"?"JFT Core":x==="support"?(id?"Pendukung":"補助"):"JLPT / Lanjutan"}</button>)}</div></section>
 <section className="grid gap-4 lg:grid-cols-2">{items.map(book=><Link key={book.id} href={`/${locale}/library/${book.id}`} className="card group p-5 transition hover:-translate-y-1"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300"><BookMarked/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{book.title}</h2><span className={`badge ${priorityStyle[book.jftPriority]}`}>{book.jftPriority==="core"?"JFT Core":book.jftPriority==="support"?"Support":"Outside JFT"}</span><span className="badge border-slate-200 dark:border-slate-700">{book.level}</span></div><div className="mt-1 text-xs font-bold uppercase tracking-wide text-slate-400">{book.series} · {book.kind}</div><p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{book.description}</p><div className="mt-4 flex items-center justify-between text-sm"><span className="font-semibold text-slate-500">{book.chapters.length?`${book.chapters.length} ${id?"bab/unit":"章/ユニット"}`:(id?"Koleksi sumber":"資料コレクション")}</span><ChevronRight className="transition group-hover:translate-x-1" size={18}/></div></div></div></Link>)}</section></div>
}
