"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { CheckCircle2, Play, RotateCcw, XCircle } from "lucide-react";
import type { BookChapter, BookResource, Category, Locale } from "@/types";
import { chapterQuizQuestions } from "@/data/chapterQuiz";
import { markStudyActivity, recordAttempt } from "@/lib/progress";
function speak(text:string){if(typeof window==="undefined"||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.92;const v=speechSynthesis.getVoices().filter(x=>x.lang.toLowerCase().startsWith("ja"));if(v.length)u.voice=v[0];speechSynthesis.speak(u)}
export function ChapterQuiz({locale,book,chapter}:{locale:Locale;book:BookResource;chapter:BookChapter}){
 const id=locale==="id"; const qs=useMemo(()=>chapterQuizQuestions(book.id,chapter,20),[book.id,chapter]); const [idx,setIdx]=useState(0); const [answers,setAnswers]=useState<Record<string,number>>({}); const [done,setDone]=useState(false); const [plays,setPlays]=useState<Record<string,number>>({}); const q=qs[idx]; const selected=answers[q.id]; const answered=selected!==undefined; const correct=qs.filter(x=>answers[x.id]===x.correctIndex).length;
 const finish=()=>{const pct=Math.round(correct/qs.length*100);const categoryScores:Partial<Record<Category,number>>={};for(const c of ["vocabulary","grammar","listening","reading"] as Category[]){const g=qs.filter(x=>x.category===c);categoryScores[c]=Math.round(g.filter(x=>answers[x.id]===x.correctIndex).length/g.length*100)}recordAttempt({type:"chapter",title:`${book.title} · ${chapter.title}`,correct,total:qs.length,pct,categoryScores});setDone(true)};
 if(done){const pct=Math.round(correct/qs.length*100);return <div className="mx-auto max-w-3xl space-y-5"><div className="card p-8 text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-emerald-50 text-3xl font-black text-emerald-700 dark:bg-emerald-950/40">{pct}%</div><h1 className="mt-4 text-3xl font-black">{id?"Tes bab selesai":"章テスト完了"}</h1><p className="mt-2 text-slate-500">{correct}/{qs.length} {id?"jawaban benar":"正解"}</p><p className="mt-3 text-sm text-slate-500">{pct>=80?(id?"Bab ini sudah cukup kuat. Lanjut ke bab berikutnya atau ulang untuk konsistensi.":"この章は十分定着しています。次へ進めます。"):(id?"Ulangi kosakata dan pola bab, lalu coba tes sekali lagi.":"語彙と文型を復習して再挑戦しましょう。")}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={()=>location.reload()} className="btn-primary"><RotateCcw size={17}/>{id?"Ulang tes":"再挑戦"}</button><Link href={`/${locale}/library/${book.id}/${chapter.id}`} className="btn-ghost border border-slate-200 dark:border-slate-700">{id?"Kembali belajar":"学習へ戻る"}</Link></div></div></div>}
 return <div className="mx-auto max-w-4xl space-y-4"><div className="soft-card flex items-center justify-between p-4"><div><div className="text-xs font-black uppercase tracking-wider text-emerald-600">{book.title}</div><div className="font-black">{chapter.title}</div></div><div className="text-right"><div className="text-xs text-slate-500">{id?"Soal":"問題"}</div><div className="font-black">{idx+1}/{qs.length}</div></div></div><div className="card p-5 md:p-8"><div className="mb-5 flex items-center justify-between"><div className="flex flex-wrap gap-2"><span className="badge border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{q.category}</span><span className="badge border-slate-200 dark:border-slate-700">{q.subcategory}</span></div>{q.category==="listening"&&<button disabled={(plays[q.id]||0)>=2} onClick={()=>{setPlays({...plays,[q.id]:(plays[q.id]||0)+1});speak(q.audioText||q.promptJa||q.prompt)}} className="btn-ghost border border-slate-200 dark:border-slate-700"><Play size={17}/>{id?"Putar audio":"音声"} {plays[q.id]||0}/2</button>}</div><h1 className="jp whitespace-pre-line text-xl font-bold leading-relaxed md:text-2xl">{q.promptJa||q.prompt}</h1><div className="mt-6 grid gap-3">{(q.optionsJa||q.options).map((o,i)=>{const good=answered&&i===q.correctIndex,wrong=answered&&i===selected&&i!==q.correctIndex;return <button disabled={answered} onClick={()=>{setAnswers({...answers,[q.id]:i});markStudyActivity()}} key={`${o}-${i}`} className={`rounded-2xl border p-4 text-left ${good?"border-emerald-500 bg-emerald-50 dark:bg-emerald-950/30":wrong?"border-rose-500 bg-rose-50 dark:bg-rose-950/30":"border-slate-200 hover:border-slate-400 dark:border-slate-700"}`}><span className="mr-3 font-black text-slate-400">{String.fromCharCode(65+i)}</span><span className="jp">{o}</span></button>})}</div>{answered&&<div className={`mt-6 rounded-2xl p-4 ${selected===q.correctIndex?"bg-emerald-50 dark:bg-emerald-950/30":"bg-rose-50 dark:bg-rose-950/30"}`}><div className="flex items-center gap-2 font-black">{selected===q.correctIndex?<CheckCircle2 className="text-emerald-600"/>:<XCircle className="text-rose-600"/>}{selected===q.correctIndex?(id?"Benar":"正解"):(id?"Belum tepat":"不正解")}</div><p className="jp mt-2 text-sm text-slate-600 dark:text-slate-300">{id?q.explanation:(q.explanationJa||q.explanation)}</p>{q.audioText&&<p className="jp mt-3 border-t border-current/10 pt-3 text-sm">{q.audioText}</p>}</div>}<div className="mt-7 flex justify-end">{idx===qs.length-1?<button disabled={!answered} onClick={finish} className="btn-primary disabled:opacity-40">{id?"Selesai":"完了"}</button>:<button disabled={!answered} onClick={()=>setIdx(idx+1)} className="btn-primary disabled:opacity-40">{id?"Soal berikutnya":"次の問題"} →</button>}</div></div></div>
}
