"use client";
import { useEffect, useState } from "react";
import { BarChart3, BookOpenCheck, Flame, Target, TrendingUp } from "lucide-react";
import type { Category, Locale, StoredAttempt } from "@/types";
import { getAttempts, getCategoryScores, getStreak } from "@/lib/progress";

export function StatsView({locale}:{locale:Locale}){
 const id=locale==="id"; const [scores,setScores]=useState<Record<Category,number>>({vocabulary:0,grammar:0,listening:0,reading:0}); const [attempts,setAttempts]=useState<StoredAttempt[]>([]); const [streak,setStreak]=useState({current:0,best:0,activeDays:[] as string[]});
 useEffect(()=>{setScores(getCategoryScores());setAttempts(getAttempts());setStreak(getStreak())},[]);
 const entries=Object.entries(scores) as [Category,number][]; const active=entries.filter(([,v])=>v>0); const weakest=active.length?[...active].sort((a,b)=>a[1]-b[1])[0]:null; const strongest=active.length?[...active].sort((a,b)=>b[1]-a[1])[0]:null;
 const solved=attempts.reduce((n,a)=>n+a.total,0); const avg=attempts.length?Math.round(attempts.reduce((n,a)=>n+a.pct,0)/attempts.length):0;
 return <div className="space-y-6"><div><h1 className="text-3xl font-black">{id?"Statistik Belajar":"学習統計"}</h1><p className="mt-2 text-slate-500">{id?"Try Out, Drilling, tes bab, Listening, dan streak dirangkum dari aktivitas di browser ini.":"模試・ドリル・章テスト・聴解・ストリークをこのブラウザの学習履歴から集計します。"}</p></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="soft-card p-4"><BookOpenCheck className="text-emerald-600"/><div className="mt-3 text-2xl font-black">{solved}</div><div className="text-sm text-slate-500">{id?"Soal dikerjakan":"解答数"}</div></div><div className="soft-card p-4"><Target className="text-blue-600"/><div className="mt-3 text-2xl font-black">{avg}%</div><div className="text-sm text-slate-500">{id?"Rata-rata":"平均正答率"}</div></div><div className="soft-card p-4"><TrendingUp className="text-violet-600"/><div className="mt-3 text-2xl font-black capitalize">{strongest?strongest[0]:"—"}</div><div className="text-sm text-slate-500">{id?"Terkuat":"最強カテゴリ"}{strongest?` · ${strongest[1]}%`:""}</div></div><div className="soft-card p-4"><Flame className="text-amber-600"/><div className="mt-3 text-2xl font-black">{streak.current}</div><div className="text-sm text-slate-500">{id?"Hari streak":"連続学習日"} · best {streak.best}</div></div></div>
 <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="card p-5"><div className="flex items-center gap-2"><BarChart3/><h2 className="font-black">{id?"Kemampuan per kategori":"カテゴリ別"}</h2></div><div className="mt-6 space-y-5">{entries.map(([k,v])=><div key={k}><div className="mb-2 flex justify-between text-sm"><span className="capitalize font-semibold">{k}</span><span>{v}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{width:`${v}%`}}/></div></div>)}</div></div><div className="card p-5"><h2 className="font-black">{id?"Rekomendasi otomatis":"自動おすすめ"}</h2>{weakest?<><div className="mt-4 rounded-2xl bg-amber-50 p-4 dark:bg-amber-950/30"><div className="text-sm font-bold capitalize">{weakest[0]} · {weakest[1]}%</div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{id?"Lakukan Drilling 20 soal pada kategori ini, lalu cek kembali akurasinya.":"このカテゴリを20問ドリルして正答率を再確認。"}</p></div>{strongest&&<div className="mt-3 rounded-2xl bg-emerald-50 p-4 dark:bg-emerald-950/30"><div className="text-sm font-bold capitalize">{strongest[0]} · {strongest[1]}%</div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{id?"Pertahankan dengan latihan singkat.":"短い復習で維持。"}</p></div>}</>:<p className="mt-4 text-sm text-slate-500">{id?"Belum ada hasil. Mulai satu sesi Drilling atau Try Out.":"まだ結果がありません。ドリルまたは模試を始めてください。"}</p>}</div></div></div>
}
