"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Flag, LockKeyhole, Play, Send } from "lucide-react";
import type { Category, Locale } from "@/types";
import { questionsForTryout } from "@/data/drillingBank";
import { allTryouts } from "@/data/sourceInventory";
import { markStudyActivity, recordAttempt } from "@/lib/progress";

const sectionOrder=["vocabulary","grammar","listening","reading"] as const;
function speak(text:string,voiceType?:"male"|"female"){
  if(typeof window==="undefined"||!("speechSynthesis" in window)) return;
  speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.92;
  const voices=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith("ja"));
  if(voices.length)u.voice=voices[voiceType==="male"&&voices.length>1?1:0]; speechSynthesis.speak(u);
}
export function TryoutRunner({locale,id}:{locale:Locale;id:string}){
  const def=allTryouts.find(x=>x.id===id); const seed=Math.max(1,allTryouts.findIndex(x=>x.id===id)+1);
  const qs=useMemo(()=>questionsForTryout(seed,50,def?.packageId),[seed,def?.packageId]); const router=useRouter();
  const [idx,setIdx]=useState(0); const [answers,setAnswers]=useState<Record<string,number>>({}); const [flags,setFlags]=useState<Record<string,boolean>>({});
  const [submitted,setSubmitted]=useState(false); const [secondsLeft,setSecondsLeft]=useState(3600); const [playCount,setPlayCount]=useState<Record<string,number>>({});
  const [questionMode,setQuestionMode]=useState<"source"|"ja">("ja");
  const idn=locale==="id"; const recorded=useRef(false);
  useEffect(()=>{const saved=localStorage.getItem("kezett-question-mode");if(saved==="source"||saved==="ja")setQuestionMode(saved)},[]);
  const q=qs[idx]; const currentSection=q.category; const sectionStart=qs.findIndex(x=>x.category===currentSection);
  const correct=qs.filter(x=>answers[x.id]===x.correctIndex).length; const pct=Math.round(correct/qs.length*100);
  useEffect(()=>{if(submitted)return;const timer=window.setInterval(()=>setSecondsLeft(s=>{if(s<=1){window.clearInterval(timer);setSubmitted(true);return 0}return s-1}),1000);return()=>window.clearInterval(timer)},[submitted]);
  useEffect(()=>{if(submitted&&def&&!recorded.current){recorded.current=true;const categoryScores={} as Record<Category,number>;for(const cat of sectionOrder){const group=qs.filter(x=>x.category===cat);categoryScores[cat]=Math.round(group.filter(x=>answers[x.id]===x.correctIndex).length/group.length*100)}recordAttempt({type:"tryout",title:def.title,correct,total:qs.length,pct,categoryScores})}},[submitted,def,qs,answers,correct,pct]);
  if(!def)return <div className="card p-8">Try Out tidak ditemukan.</div>;
  const clock=`${String(Math.floor(secondsLeft/60)).padStart(2,"0")}:${String(secondsLeft%60).padStart(2,"0")}`;
  const categoryPct=(cat:string)=>{const a=qs.filter(x=>x.category===cat);const c=a.filter(x=>answers[x.id]===x.correctIndex).length;return Math.round(c/a.length*100)};
  if(submitted)return <div className="space-y-5"><div className="card p-7 text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-emerald-50 text-3xl font-black text-emerald-700 dark:bg-emerald-950/50">{pct}%</div><h1 className="mt-4 text-3xl font-black">{idn?"Simulasi selesai":"模試完了"}</h1><p className="mt-2 text-slate-500">{correct}/{qs.length} {idn?"jawaban benar":"正解"}</p><p className="mx-auto mt-4 max-w-xl text-sm text-slate-500">{idn?"Nilai ini adalah practice accuracy, bukan konversi skor resmi JFT 10–250.":"これは練習正答率であり、JFT公式10–250点への換算ではありません。"}</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{sectionOrder.map(s=><div key={s} className="soft-card p-4"><div className="text-sm capitalize text-slate-500">{s}</div><div className="mt-1 text-2xl font-black">{categoryPct(s)}%</div></div>)}</div><button className="btn-primary" onClick={()=>router.push(`/${locale}/statistik`)}>{idn?"Lihat statistik":"学習統計を見る"}</button></div>;
  const canPrev=currentSection!=="listening"&&idx>sectionStart; const canNext=idx<qs.length-1;
  const goNext=()=>{if(!canNext)return;const next=qs[idx+1];if(next.category!==currentSection){const ok=confirm(idn?"Setelah pindah bagian, kamu tidak dapat kembali. Lanjutkan?":"次のセクションへ進むと戻れません。続けますか？");if(!ok)return;}setIdx(idx+1)};
  const prompt=questionMode==="ja"?(q.promptJa||q.prompt):q.prompt; const options=questionMode==="ja"?(q.optionsJa||q.options):q.options;
  return <div className="space-y-4">
    <div className="soft-card flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`badge ${def.status==="verified"?"border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300":"border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300"}`}>{def.status==="verified"?"✓ Verified":"↻ Reconstructed"}</span><span className="badge border-slate-200 dark:border-slate-700">{def.title}</span></div><div className="mt-3 inline-flex rounded-xl border border-slate-200 bg-white p-1 dark:border-slate-700 dark:bg-slate-900"><button onClick={()=>{setQuestionMode("source");localStorage.setItem("kezett-question-mode","source")}} className={`rounded-lg px-3 py-1.5 text-xs font-black ${questionMode==="source"?"bg-slate-900 text-white dark:bg-white dark:text-slate-900":"text-slate-500"}`}>Sumber</button><button onClick={()=>{setQuestionMode("ja");localStorage.setItem("kezett-question-mode","ja")}} className={`rounded-lg px-3 py-1.5 text-xs font-black ${questionMode==="ja"?"bg-slate-900 text-white dark:bg-white dark:text-slate-900":"text-slate-500"}`}>日本語</button></div></div><div className="flex items-center gap-5 text-right"><div><div className="text-xs text-slate-500">Time left</div><div className={`font-mono text-lg font-black ${secondsLeft<300?"text-rose-600":""}`}>{clock}</div></div><div><div className="text-xs text-slate-500">Question</div><div className="font-black">{idx+1}/{qs.length}</div></div></div></div>
    <div className="grid gap-4 lg:grid-cols-[1fr_280px]"><div className="card p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><div className="flex flex-wrap gap-2"><span className="badge border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/50 dark:text-emerald-300">{currentSection}</span>{q.subcategory&&<span className="badge border-slate-200 dark:border-slate-700">{q.subcategory}</span>}{q.level&&<span className="badge border-slate-200 dark:border-slate-700">{q.level}</span>}</div><button onClick={()=>setFlags({...flags,[q.id]:!flags[q.id]})} className={`btn-ghost ${flags[q.id]?"text-amber-600":""}`}><Flag size={18}/>{idn?"Ragu":"要確認"}</button></div>
      {q.category==="listening"&&<button className="mb-5 flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 font-semibold dark:border-slate-700" disabled={(playCount[q.id]||0)>=2} onClick={()=>{speak(q.audioText||q.promptJa||q.prompt,q.audioVoice);setPlayCount({...playCount,[q.id]:(playCount[q.id]||0)+1})}}><Play size={17}/>{idn?"Putar audio Jepang":"音声を再生"}<span className="text-xs text-slate-400">{playCount[q.id]||0}/2</span></button>}
      <h1 className="jp text-xl font-bold leading-relaxed md:text-2xl">{prompt}</h1><div className="mt-6 grid gap-3">{options.map((o,i)=><button key={`${o}-${i}`} onClick={()=>{setAnswers({...answers,[q.id]:i});markStudyActivity()}} className={`rounded-2xl border p-4 text-left transition ${answers[q.id]===i?"border-emerald-500 bg-emerald-50 ring-2 ring-emerald-500/20 dark:bg-emerald-950/40":"border-slate-200 hover:border-slate-400 dark:border-slate-700"}`}><span className="mr-3 font-black text-slate-400">{String.fromCharCode(65+i)}</span><span className="jp">{o}</span></button>)}</div>
      <div className="mt-8 flex items-center justify-between"><button disabled={!canPrev} onClick={()=>setIdx(idx-1)} className="btn-ghost disabled:cursor-not-allowed disabled:opacity-30">← {idn?"Previous":"前へ"}</button>{idx===qs.length-1?<button onClick={()=>setSubmitted(true)} className="btn-primary"><Send size={17}/>{idn?"Submit ujian":"提出"}</button>:<button onClick={goNext} className="btn-primary">{idn?"Next":"次へ"} →</button>}</div>
      {currentSection==="listening"&&<div className="mt-5 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950/30 dark:text-amber-300"><LockKeyhole size={16}/>{idn?"Listening bergerak maju; soal sebelumnya terkunci setelah lanjut.":"聴解は前進のみ。次へ進むと前の問題はロックされます。"}</div>}</div>
      <aside className="card h-fit p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-black">{idn?"Nomor soal":"問題番号"}</h3><span className="text-xs text-slate-500">{Object.keys(answers).length}/{qs.length}</span></div><div className="grid grid-cols-5 gap-2">{qs.map((x,i)=>{const disabled=x.category!==currentSection;return <button key={x.id} disabled={disabled} onClick={()=>!disabled&&currentSection!=="listening"&&setIdx(i)} className={`relative aspect-square rounded-lg text-xs font-bold ${i===idx?"bg-emerald-600 text-white":answers[x.id]!==undefined?"bg-emerald-100 text-emerald-800 dark:bg-emerald-950":"bg-slate-100 dark:bg-slate-800"} disabled:opacity-30`}>{i+1}{flags[x.id]&&<span className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-amber-500"/>}</button>})}</div></aside>
    </div>
  </div>;
}
